name: ar_flutter_plugin_plus
description: Flutter Plugin for Augmented Reality experiences - Supports ARKit for iOS and ARCore for Android devices.
version: 1.1.0
homepage: https://xinix.tech/
repository: https://github.com/FranzGraaf/ar_flutter_plugin_plus

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  vector_math: ^2.2.0
  json_annotation: ^4.9.0
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: tech.graaf.franz.ar_flutter_plugin_plus
        pluginClass: ArFlutterPluginPlus
      ios:
        pluginClass: ArFlutterPluginPlus
